import torch

MAX_SEQ_LEN = 256
PER_DEVICE_BATCH = 8
GRAD_ACCUM = 8
LEARNING_RATE = 1e-4
NUM_EPOCHS = 1
WARMUP_STEPS = 100
WEIGHT_DECAY = 0.01
EARLY_STOPPING_PATIENCE = 3
EARLY_STOPPING_THRESHOLD = 0.001
world_size = torch.cuda.device_count()

# Dynamic MoE parameters
ADAPTIVE_AUDIT_STEPS = 10
MAX_ROUTED_EXPERTS = 6
DYNMOE_THRESHOLD_INIT = -0.08
BIAS_UPDATE_RATE = 0.001